[dosbox]
machine=svga_s3
memsize=16

[autoexec]
mount C /doslab/src
C:
cls
echo ===========================================
echo Welcome to Node B DOSBox-X
echo ===========================================
echo Your /doslab/src folder is mounted as C:\SRC
echo Connects to Node A on TCP null-modem port 5000
pause

[serial]
serial1=nullmodem transparent:1 host:node-a port:5000
serial2=disabled

[mounts]
mount c /doslab/src
c:
